#!/usr/bin/env bash

# Change it depending on your OS
export XDEBUG_HOST='docker.for.mac.localhost' # Specific to OSX
#export XDEBUG_HOST=$(/sbin/ip route|awk '/kernel.*metric/ { print $9 }') # Specific to Linux

if [ $# -gt 0 ]; then
    docker-compose -f infrastructure/docker/docker-compose.yml "$@"
    if [[ "$@" == *"up"* ]]; then
        echo ""
        echo "Add this to your '/etc/hosts': '0.0.0.0 demo.viscat.local'"
        echo "Then you can visit: 'http://demo.viscat.local'"
        echo ""
    fi
else
docker-compose -f infrastructure/docker/docker-compose.yml ps
fi
