---
- name: Demo app provisioning
  hosts: all

  remote_user: ubuntu
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    owner: deploy

  pre_tasks:
    - name: Add PHP repo
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present
        update_cache: yes

    - name: Adding Apache repo
      apt_repository:
        repo: "ppa:ondrej/apache2"
        state: present
        update_cache: yes

    - name: Ensure all apache folders are created
      file:
        name: "/var/www/{{ item }}"
        state: directory
        owner: "{{ owner }}"
        group: www-data
        mode: 0775
      with_items:
        - app

  roles:
    - role: geerlingguy.php
      php_version: 7.1

    - role: geerlingguy.php-xdebug
      php_xdebug_remote_enable: "true"
      php_xdebug_remote_connect_back: "false"
      php_xdebug_remote_host: localhost
      php_xdebug_remote_port: "9000"
      php_xdebug_remote_autostart: "true"
      php_xdebug_idekey: docker

    - role: geerlingguy.composer

    - role: geerlingguy.apache
      apache_remove_default_vhost: true
      apache_create_vhosts: true
      apache_vhosts_filename: "vhosts.conf"
      apache_state: restarted
      apache_vhosts:
        - servername: "demo.viscat.local"
          extra_parameters: |
            DocumentRoot /var/www/app/public
            <Directory "/var/www/app/public">
              AllowOverride None
              Options -Indexes -MultiViews +FollowSymLinks
              Require all granted
              <IfModule mod_rewrite.c>
                RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^(.*)$ index.php [QSA,L]
              </IfModule>
            </Directory>
            ErrorLog  /var/log/apache2/app-error.log
            CustomLog /var/log/apache2/app-access.log combined

    - role: geerlingguy.nodejs
